// ============================================================================
//  One-off generator: extract the Rig 103 WCE register + P&ID from the source
//  Excel into a typed data module (RIG103_EQUIPMENT + RIG103_TEMPLATE).
//  Source: "WCE REGISTER PLUS P&ID 2026.xlsx" (hand-drawn P&ID + register).
//  Run:  node scripts/gen-rig103.mjs "<path-to-xlsx>"
//  Output: src/lib/data/rig103-equipment.ts
// ============================================================================
import * as XLSX from 'xlsx';
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = process.argv[2] || String.raw`C:\Users\80128\Downloads\WCE REGISTER PLUS P&ID 2026.xlsx`;
const wb = XLSX.read(readFileSync(SRC), { type: 'buffer' });
const ws = wb.Sheets['WELL CONTROL EQUIPMENT'];
const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '', blankrows: false });

// Excel serial → ISO yyyy-mm-dd (blank for non-dates / placeholders).
const EPOCH = Date.UTC(1899, 11, 30);
function isoDate(v) {
  const n = typeof v === 'number' ? v : Number(String(v).trim());
  if (!Number.isFinite(n) || n < 20000 || n > 80000) return '';
  return new Date(EPOCH + n * 86400000).toISOString().slice(0, 10);
}

// Map a free-text equipment description to a library symbol key.
function mapType(d) {
  const s = d.toLowerCase();
  if (s.includes('annular')) return 'annular';
  if (s.includes('ram') || s.includes('element bop')) return 'dram';
  if (s.includes('mud cross')) return 'cross';
  if (s.includes('dsa') || s.includes('flange') || s.includes('adapter')) return 'flange';
  if (s.includes('coflex') || s.includes('hose')) return 'hose';
  if (s.includes('nrv')) return 'check';
  if (s.includes('hcr')) return 'hcr';
  if (s.includes('choke')) return 'choke';
  if (s.includes('relief')) return 'relief';
  if (s.includes('pulsation') || s.includes('dampner') || s.includes('dampener')) return 'dampener';
  if (s.includes('goose') || s.includes('swivel')) return 'gooseneck';
  if (s.includes('stump')) return 'teststump';
  if (s.includes('accumulator')) return 'accum';
  if (s.includes('control unit') || s.includes('control panel') || s.includes('koomey')) return 'control';
  if (s.includes('degasser') || s.includes('mgs') || s.includes('poorboy')) return 'mgs';
  if (s.includes('triplex') || s.includes('mud pump')) return 'mudpump';
  if (s.includes('air pump') || s.includes('electrical pump') || s.endsWith('pump')) return 'pump';
  if (s.includes('manifold')) return 'manifold';
  if (s.includes('kelly') || s.includes('ibop') || s.includes('fosv') || s.includes('gray valve')) return 'kelly';
  if (s.includes('spool')) return 'pipe';
  if (s.includes('pipe')) return 'pipe';
  if (s.includes('valve')) return 'gate';
  return 'gate';
}

const equipment = [];
const placements = [];
let section = '';
// by-section grid layout
const PER_ROW = 8, COL_W = 130, ROW_H = 132, MARGIN_X = 90, SEC_GAP = 80;
let curY = 90, secIdx = 0;
let secStartCount = 0;

function flushSectionSpacing(count) {
  curY += Math.ceil(count / PER_ROW) * ROW_H + SEC_GAP;
}

for (let i = 3; i < rows.length; i++) {
  const r = rows[i].map((c) => String(c).trim());
  const desc = r[0];
  if (!desc) continue;
  const hasData = r.slice(1).some((c) => c !== '');
  if (!hasData) { // section header
    if (secIdx > 0) flushSectionSpacing(secStartCount);
    section = desc.replace(/\s+/g, ' ');
    secIdx++; secStartCount = 0;
    continue;
  }
  const type = mapType(desc);
  const tag = r[6] || '';
  const asset = {
    type, section, description: desc.replace(/\s+/g, ' '), tag,
    rwp: r[1] || '', size: r[2] || '', manufacturer: r[3] || '', serial: r[5] || '',
    int_last: isoDate(r[8]), int_due: isoDate(r[9]), maj_last: isoDate(r[11]), maj_due: isoDate(r[12]),
  };
  equipment.push(asset);
  const col = secStartCount % PER_ROW, row = Math.floor(secStartCount / PER_ROW);
  placements.push({ type, tag, name: asset.description.slice(0, 40), x: MARGIN_X + col * COL_W, y: curY + row * ROW_H, rot: 0 });
  secStartCount++;
}

const out = `// AUTO-GENERATED by scripts/gen-rig103.mjs from "WCE REGISTER PLUS P&ID 2026.xlsx".
// Rig 103 HP Well Control Equipment register (hand-drawn source P&ID) — extracted
// to a typed dataset + a tidy by-section layout. Tags are the source P&ID numbers.
import type { AempAsset, TemplateItem } from '../../types';

export const RIG103_EQUIPMENT: AempAsset[] = ${JSON.stringify(equipment)};

export const RIG103_TEMPLATE: TemplateItem[] = ${JSON.stringify(placements)};
`;
writeFileSync('src/lib/data/rig103-equipment.ts', out);
console.log(`Wrote ${equipment.length} equipment rows + ${placements.length} placements across ${secIdx} sections.`);
const types = {};
for (const e of equipment) types[e.type] = (types[e.type] || 0) + 1;
console.log('type counts:', JSON.stringify(types));
